### ISSUE TITLE
[resolved]Radiant: clipboard

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#15]
Hi,
I did not used any example data. I just checked "clipboard" to paste some thing. The default data is diamonds. 

Dear Dr Vincent,

Using this link, the clipboard works correctly .
When I use actual R version
library('radiant')
radiant('quant')

or R devel from GitHub.

shiny::runApp('inst/quant')

The text area does not appear and when I clic on "paste data",  the R session aborted with this message:
incompatible final line found by readTableHeader on 'pbpaste'

Thanks for help,
Karim

**Comment by vnijs** [comment]
@kmezhoud Copy and paste works a little differently depending if you are running Radiant locally or on a server. When run on a server you see a text box to put data in. Locally, however, R can access the content of the clipboard directly. Copy some data in Excel and hit Paste in Radiant and your data should show up (assuming it is reasonably formatted). 

I just pushed an update that should catch errors due to an empty clipboard. Please update and let me know (see command below).

```r
update.packages(checkBuilt = TRUE, ask = FALSE, type = "binary", repos = "http://vnijs.github.io/radiant_miniCRAN/")
```

**Comment by kmezhoud** [comment]
Hi,
Yes that works.
Thanks

**Comment by vnijs** [comment]
Thanks for letting me know @kmezhoud. FYI No need to change the issue title. Just 'close' the issue.
