### ISSUE TITLE
pivotr_ui V0.2.51

### ISSUE THREAD

**Issue by kmezhoud** [vnijs/radiant#24]
Hi,
I expect that the previous version of pivotr_ui is the future for complexe data visualisation. it makes free the choice of variables and the plot style (treemap...). the user is free to combine variables depending of its data to get significant view.
I did not note the advantages of the last version of pivotr_ui.

https://github.com/vnijs/radiant/blob/8462695ef30df38fccacc2564dea2d038c842fc3/inst/base/tools/help/figures/pivotr.png

**Comment by vnijs** [comment]
rpivottable is a very nice package. If you prefer it and want to make changes to your fork you have an example in the previous versions of the Radiant code base on github. rpivottable is basically a stand-alone app that was grafted onto Radiant and would be very difficult to integrate fully the way I want. It also is much slower than even the first implementation of the new pivot tab because it has to do all processing client-side. Try loading a 50MB file and using rpivottable. It won't work very well. Pivotr works client-side and uses dplyr so will be much faster. Especially when I find some time to rewrite the code for efficiency.

The new pivot tab already provides the main functionality I need (e.g., a table with drag-and-drop to ordering categorical variables). The added flexiblity to use pagination, sorting, searching, and filtering is important to me as well.. The main tab for creating graphs in Radiant is Data > Visualize. I might add some basic plots to the new Pivot tab as well but don't have time right now. 

Just out of curiosity, what things do you miss without rpivottable that you cannot do with the Visualize and Pivot tabs in Radiant? An example with data would be useful.

**Comment by cam333** [comment]
@vnijs , 

I ran into the same issue.  Rpivottable is great, but slow - I had it in my app, but as the data grew it became a huge bottle neck.  I really like how you have used DT and sidebar options to replace the main functionality of rpivottable.  I believe this is along the lines of what I'll have to build in order to handle larger data sets.

**Comment by vnijs** [comment]
@cam333 Thanks for the comments. Whatever you build be sure to use dplyr (or data.table) to do the processing. Just curious ... what are you working on that you used rpivottable for?

**Comment by cam333** [comment]
@vnijs, I'll definitely be using dplyr.  I was using rpivottable to look at hourly electricity load data across different zones.  The category variables are things like 'On Peak', 'Off Peak' hours.  The row names become compounded, when for example, I want to see a sub set of hours inside 'On Peak', aka 'Super Peak'.  11 zones and 5 years of hourly data was too big for rpivottable...

**Comment by vnijs** [comment]
@cam333 Thanks for the information. @kmezhoud I'll close this for now. If you have further comments feel free to open a new issue

**Comment by kmezhoud** [comment]
@vnijs & @cam333 
Sorry for the delay and thanks for your comments.
I am thinking about conditional formatting. there are two choices (color bar and heat map) in the last version. In previous version, there are for example Treemap or scatters. May be I will add some conditional formatting, useful for biology.
@vnijs yes it is right about rpivottable is slow.
I like the new pivot panel ;) .
Good Job,
Thanks

**Comment by vnijs** [comment]
Glad to hear it @cam333
