### ISSUE TITLE
Error: package ‘radiant’ is available as a source package but not as a binary

### ISSUE THREAD

**Issue by yugaryzhou** [vnijs/radiant#38]
> install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/", type = "binary")
Installing package into ‘C:/Users/epcil_000/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

   package ‘radiant’ is available as a source package but not as a binary

Warning message:
package ‘radiant’ is not available (as a binary package for R version 3.2.2) 
>

**Comment by vnijs** [comment]
Thanks for reporting! Back up now.

**Comment by yugaryzhou** [comment]
Now the error do not exist, another error comes
> install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/", type = 'binary')
Installing package into ‘C:/Users/epcil_000/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://vnijs.github.io/radiant_miniCRAN/bin/windows/contrib/3.2/radiant_0.3.67.zip'
Content type 'application/zip' length 12864815 bytes (12.3 MB)
downloaded 12.3 MB

package ‘radiant’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\epcil_000\AppData\Local\Temp\RtmpCOlX3g\downloaded_packages
> radiant::launcher("marketing")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘httpuv’
>

**Comment by vnijs** [comment]
Hmmm. `install.packages` should install that dependency automatically. As it hasn't in this case you can install httpuv from the same repos:

install.packages("httpuv", repos = "http://vnijs.github.io/radiant_miniCRAN/", type = 'binary')

Note that I have seen this type of error pop-up once or twice. Not clear why it doesn't install all dependencies. I expect this is an R-issue rather than a Radiant issue though but I can't replicate it
